sprint-team3/GGF

- src/constants/index.ts
- src/constants/queryClient.ts
- src/hooks/useSignin.ts
- src/pages/_app.tsx
- src/stores/useUserStore.ts
- src/utils/index.ts
- src/utils/queryClient.ts
- src/utils/signout.ts
- issue: #4
- close #4
- app.tsx에서 provider 사용
- react query devtools 사용
- queryClient 생성. 옵션 값은 상의 후 변경
- useSignin hook 구현
- useMutation사용
- response로 온 accessToken과 refreshToken을 쿠키에 저장(js-cookie 라이브러리 사용)
- useUserStore에 유저 정보 저장
- isError, mutation 리턴 
- utils/signout.ts 구현
- 모든 토큰 쿠키에서 제거
- useUserStore에서 유저 정보 삭제
- queryClient 옵션 설정이 더 필요할 것 같습니다. 회의 시간에 같이 수정하면 좋을 것 같습니다!
- signout 함수에서 보완하거나 수정할 부분이 있을까요?
제가 생각했을 때는 로그아웃시 모든 토큰을 제거하고 로그인 화면으로 이동시키는 게 자연스럽다고 생각하여 이렇게 구현하였습니다.
- 이외에도 수정할 부분이 있거나 코드 관련 궁금한 부분이 있으시면 편하게 코멘트 부탁드립니다😃
> Feat[#4] : useSignin, signout, queryClient 구현

- src/components/commons/TextField/TextField.module.scss
- src/components/commons/TextField/index.tsx
- src/styles/mixins/_scrollbar.scss
- issue: #45 
- close #45
- InputField와 같이 react hook form 적용하였고, 사용하는 컴포넌트에서 FormProvider로 form을 씌워주고, useForm에서 methods 설정해주셔야 합니다.
- 구체적인 사용법은 추후 노션에 올리겠습니다.
1. label : 제목입니다.
2. name : 데이터 전송 및 유효성 검사때 사용되는 이름입니다. 
3. maxLength : 최대 길이로 기본값은 700자입니다.
4. placeholder 
5. autocomplete
- TextField에서 사용하는 두꺼운 스크롤바와 select box에서 사용하는 얇은 스크롤바를 믹스인에 추가했습니다.
- textarea와 글자수를 보여주는 div를 div로 감쌌습니다.
- focus시 border 컬러를 바꿔줘야하는 기능 때문에 isFocused라는 useState를 사용했습니다.
- div는 원래 인터렉션이 일어나면 안 되는 태그이지만, 부득이하게 이렇게 클릭 이벤트를 넣었습니다.  대신 웹접근성을 위해 tabIndex와  onKeyDown 이벤트를 추가했습니다. 이것들을 빼버리면 a11y에서 감지하는 오류가 발생합니다.
- handleKeyDown을 우선 만들긴 했는데, 과연 실효성이 있을 지 모르겠습니다. 어떤 키를 감지해서 처리해주는 게 좋을까요? 
- autocomplete를 혹시나 쓸 수도 있을 것 같아 우선 props 타입에 추가해두었는데요, 사용하지 않을 것 같다면 빼겠습니다.
> Feat[#45]: 공용 TextField 컴포넌트 구현

- src/components/commons/InputRadio/InputRadio.module.scss
- src/components/commons/InputRadio/index.tsx
- src/constants/index.ts
- src/constants/radioOptions.ts
- issue: #54  
- close #54
- 객체를 prop으로 받아 radio type input 버튼 그룹을 만드는 컴포넌트입니다.
- react hook form으로 값을 form에 넘겨줍니다.
- 페이지 로드시 첫 번째 라디오가 클릭되도록 useRef와 useState를 사용했습니다.
- fieldset과 legend를 사용해 웹 접근성을 높였습니다. 
- legend에는 input radio 옵션들에 대한 설명을 써주시면 됩니다.
- 자세한 사용법은 추후 노션에 업데이트 하겠습니다.
1. 모집 유형 객체를 radioOptions.ts에 객체로 만들었는데, 더나은 변수명/파일명이 있을 지 궁금합니다.
> Feat[#54]: 공용 InputRadio 컴포넌트 구현

- src/components/commons/inputs/TextField.module.scss
- src/components/commons/inputs/TextField.tsx
- issue: #
- close #
- TextField에서 라벨을 사용하지 않을때, focus될 시 border 컬러를 primary로 변경하였습니다.
-
-
-
-
-
> Hotfix: label없을 때 focus되면 border-color primary로 변경

- src/components/layout/empty/EmptyCard/EmptyCard.module.scss
- issue: #
- close #
- EmptyCard 의 높이를 flex-grow에서 고정값 20rem으로 수정
-
-
-
-
-
> Hotfix: EmptyCard 높이 고정값으로 수정

- src/components/commons/inputs/InputField.module.scss
- src/components/commons/inputs/InputField.tsx
- issue: #
- close #
- Inputfield에도 실시간 글자수 기능을 적용했습니다.
- isLimited 프롭을 옵셔널로 추가하였습니다
- isLimited가 true이고 type이 password가 아닐 때 작동합니다.
- isLimited : true면 실시간 글자수가 표시됩니다.
- maxLength와 minLength: 최대/최소 글자수로 isLimited를 사용할 떄는 필수로 넘겨주어야 합니다.
> Hotfix: inputfield 실시간 글자수 구현

- src/components/AccountForm/AccountForm.module.scss
- src/components/AccountForm/index.tsx
- src/components/layout/header/Header/index.tsx
- src/components/mypage/MypageContent/index.tsx
- src/constants/index.ts
- src/constants/inputNames.ts
- src/constants/inputValidation.ts
- src/constants/mockData/headerMockData.ts
- src/pages/account/index.tsx
- issue: #138 
- close #138
- Account 페이지 구현
- form에서 사용하는 input의 name들을 constants/inputNames.ts에 객체로 추가했습니다.
- headerMockData의 userData 객체 스네이크 케이스로 변경하면서, 참조하던 다른 파일도 수정했습니다.
- 프로필 이미지 첨부 및 초기화
- 프로필 폼에서 저장 버튼 클릭시 프로필이미지, 닉네임 전송
- 패스워드 폼에서 저장 버튼 클릭시 새 비밀번호 전송
- 필드별 스키마 유효성 검사
- 저장 버튼 클릭시 모달 on
- 모바일 반응형 구현
- 폼을 2개로 분리하여 버튼이 2개 생겼습니다.
- 버튼 색상을 보라색으로 변경하였습니다.
https://github.com/sprint-team3/GGF/assets/92169354/8c5d7e73-9899-481a-87cf-ede943f6d199
- `constants/inputNames.ts` 에 각자 폼에서 사용하시는 input name들 저장해서 관리하면 좋을 것 같습니다.
- form을 3개나 사용하는 페이지라 onSubmit 함수를 미리 넣어두는 게 편해서 console.log를 찍었습니다... 양해 바랍니다😂
> Feat[#138]: account 페이지 구현, inputValidation 수정, inputNames.ts 추가

- src/apis/activities.ts
- src/apis/myActivities.ts
- src/apis/myNotifications.ts
- src/apis/myReservations.ts
- src/components/commons/Pagination/index.tsx
- src/components/mypage/MyPosts/MyPosts.module.scss
- src/components/mypage/MyPosts/index.tsx
- src/components/mypage/MypageContent/index.tsx
- src/constants/paging.ts
- src/constants/postTypes.ts
- src/hooks/usePaginatedDataList.ts
- src/utils/getPageSize.ts
- issue: #98 
- close #98 
- 마이페이지 - 등록한 게시글 탭 컨텐츠 구현
- 데이터 수정/삭제 등을 제외한 페이지 기능 구현
- [공용 기능] 디바이스 타입에 따라 페이지 사이즈를 초기화 해주는 유틸함수 추가 (게시글/리뷰)
- [공용 기능] usePaginatedDataList 훅에서 페이지 사이즈가 변경되면 활성화된 페이지를 1로 초기화하도록 수정
- [공용 기능] useFilteredDataList 훅에서 필터 키의 값이 'all' 일땐 해당 키에 대한 필터링을 하지 않도록 수정
- [공용 컴포넌트] Filter 컴포넌트의 이벤트 핸들러를 일반 화살표함수로 변경하고, 선택된 필터 ID를 인자로 받도록 수정
- 필터, 드롭다운, 카드, 페이징 컴포넌트를 조합해서 페이지 UI 작업 완료
- 모바일 사이즈 대응 완료
https://github.com/sprint-team3/GGF/assets/43297823/f5e79031-caad-4025-9009-8b09e42d0177
> Feat[#98]: 마이페이지 - 등록한 게시글 탭 컨텐츠 구현

- src/components/commons/Kebabmenu/Kebabmenu.module.scss
- src/components/commons/Kebabmenu/index.tsx
- src/components/commons/buttons/MoreButton.tsx
- src/components/mypage/MyPosts/MyPosts.module.scss
- src/components/mypage/MyPosts/index.tsx
- 마이페이지의 등록한 게시글 탭 버그 수정, 스타일 수정, 리팩터링
- 카드 컴포넌트의 Link 태그 때문에 케밥메뉴를 클릭했을 때 링크이동이 되는 오류 수정 -> `event.preventDefault()`
- Sort Opion 을 상수에서 불러와서 사용
- 정렬 드롭다운을 디바이스 타입에 따라 두개 만들었던 것을 하나로 합치고, `position: absolute` 로 위치만 이동시킴
- 케밥버튼이 케밥메뉴를 뚫고 나오는 오류 수정 -> `케밥메뉴의 z-index 제거`
> Fix: 마이페이지 - 등록한 게시글 탭 수정사항 반영

- src/components/postDetail/ImageModal/ImageModal.module.scss
- src/components/postDetail/ImageModal/index.tsx
- src/components/postDetail/ImageSlide/ImageSlide.module.scss
- src/components/postDetail/ImageSlide/index.tsx
- src/constants/mockData/imageList.ts
- src/stories/ImageModal.stories.ts
- src/stories/ImageSlide.stories.ts
- src/styles/mixins/_scrollbar.scss
- src/styles/variables/_responsive-height.scss
- issue: #173 
- close #
- 
- 이미지 주소가 있는 배열을 prop으로 받아 슬라이드를 보여줍니다.
- 좌우 버튼 클릭시, 하단 스크롤바 클릭시 슬라이드가 이동합니다.
- 슬라이드 내의 이미지 클릭시 이미지가 들어있는 모달이 보여집니다.
- 모달의 overlay 클릭시 모달이 닫힙니다.
- viewport의 크기가 줄어도, 사진의 고정 width는 줄지 않고, 컨테이너의 크기만 줄어듭니다.
- 태블릿, 모바일 반응형 구현했습니다. 모바일일 때 컨테이너 왼쪽에 1.5rem 만큼 마진 생깁니다.
1. `imageList?: string[];` : 이미지 주소가 들어있는 배열입ㅂ니다.
1. `isOpen: boolean;` : 모달의 열림상태를 나타냅니다.
2. `imageSrc: string;` : 모달에서 보여줄 image의 src입니다.
3. `onClose: MouseEventHandler<HTMLButtonElement>;` : 모달의 overlay 클릭시 모달의 열림상태를 false로 바꿔줄 함수입니다.
https://github.com/sprint-team3/GGF/assets/92169354/f2800edf-27f5-4688-b3bd-ecddcc6e7542
-
> Feat: 모집 상세 페이지의 ImageSlide, ImageModal 구현

- src/components/commons/inputs/ImageField.module.scss
- src/components/commons/inputs/ImageField.tsx
- src/stories/ImageField.stories.ts
- issue: #
- close #
- 파일 새로 첨부시 기존 리스트 다 삭제하도록 했습니다.
- 이미지 하나 x 버튼으로 삭제시, hover 효과 오작동 해결했습니다.
- 이미지 첨부된 파일 리스트가 변경될 때마다 `onFilesUpdate`로 전달되도록 했습니다.
- 이미지 첨부없을 때 보이는` flex-gap` 삭제하고, list에 `padding-top` `1.6rem` 추가했습니다.
- drag 아이콘에 `opacity transition` 적용했습니다.
- 라벨 추가했습니다.
- `label: string` 추가했습니다.
https://github.com/sprint-team3/GGF/assets/92169354/41ca1121-648e-4307-ba2c-67c9ef63f1cb
> Hotfix: ImageField 업로드 버튼 transition 추가, label 추가, x 버튼 버그 수정

- src/components/commons/inputs/DateField.module.scss
- src/components/commons/inputs/DateField.tsx
- src/utils/getDate.ts
- issue: #
- close #
1. day picker 모달에 box shadow, z-index 추가했습니다
2. 오늘로부터 30일까지만 날짜 선택할 수 있도록 day picker 수정했습니다.
> Hotfix: Datefield css수정, 30일 제한 날짜선택 추가

- src/components/commons/Avatar/index.tsx
- issue: #
- close #
- 문제:  Avartar 컴포넌트 사용시 로컬 콘솔에서 layout 프롭 사용하지 말라는 경고문구가 떴습니다.
-  해결: layout 프롭 삭제, sizes='100%' 적용했습니다.
> Hotfix: Avartar 컴포넌트 layout 프롭 삭제, sizes='100%' 적용

- src/components/commons/inputs/ImageField.module.scss
- src/components/commons/inputs/ImageField.tsx
- issue: #
- close #
1. 이미지 파일 삭제시 삭제 파일 반환하는 onFileDelete와 이미지 첨부 가능 개수인 maxfiles을 옵셔널 프롭으로 추가했습니다.
2. 이미지 첨부되지 않았을 때 리스트 영역 display none 처리했습니다.
> Hotfix: ImageField 옵셔널 프롭 및 리스트 css 수정

- src/components/commons/inputs/PostFormDropdown.module.scss
- src/components/commons/inputs/PostFormDropdown.tsx
- src/components/commons/inputs/index.ts
- src/components/createPage/PostForm/index.tsx
- src/components/createPage/Schedule/index.tsx
- issue: #
- close #
- 등록 페이지에서 사용하는 PostFormDropdown 컴포넌트 추가 및 적용
-
-
-
-
-
> Hotfix: PostFormDropdown 컴포넌트 추가 및 적용

- src/components/commons/buttons/CardButton.module.scss
- src/components/commons/buttons/CardButton.tsx
- src/components/commons/cards/ReservedCard.module.scss
- src/components/commons/cards/ReservedCard.tsx
- src/components/mypage/MyReservations/ReservedTabContent/index.tsx
- src/components/mypage/MyReservations/ReviewModalContent/index.tsx
- src/constants/games.ts
- src/stories/ReservedCard.stories.ts
- issue: #224 
- close #224
- 마이페이지 신청한 예약 API 연동했습니다.
- [GET] 내 예약 리스트 조회
- [PATCH] 내 예약 취소
- [POST] 내 예약 리뷰 작성
- 마이페이지로 이동 시 `토큰 유무`를 확인하고, 토큰이 없는 경우 `랜딩 페이지`로 `리다이렉트`합니다.
- 데이터 조회에 SSR과 react-query를 사용합니다.
- 리뷰 작성 조건: 예약 상태가 `completed`이고, 예약 날짜가 지난 경우, 예약 제출 현황이 `false`인 경우 리뷰 버튼이 표시됩니다.
- 리뷰를 작성한 후에는 `리뷰 완료` 버튼으로 변경됩니다.
- 예약은 `pending` 상태일 때만 취소할 수 있습니다.
- 예약이 확정된 이후에는 취소할 수 없습니다.
- PC 디바이스 이하에서는 예약 카드의 hover 효과를 제거했습니다.
- 리뷰 완료 버튼 스타일을 추가하였습니다.
> Feat[#224]: 마이페이지/신청한 예약 api 연동

- src/apis/activities.ts
- src/apis/queryFunctions.ts
- src/apis/queryKeys.ts
- src/components/postDetail/PostDetailContent/index.tsx
- src/constants/mockData/postDetail.ts
- src/pages/[game]/[postId]/index.tsx
- src/types/myActivities.ts
- issue: #202 
- close #202
- SSR + 리액트쿼리 사용했습니다.
- 액세스토큰 확인해서 로그인 상태 확인 후 자식 컴포넌트(예약 컴포넌트)로 전달합니다.
- 존재하지 않는 postId로 접근할 경우 게임 카테고리 리스트로 리다이렉트합니다.
- 모집 상세 데이터 조회, 리뷰 리스트 데이터 조회하는 prefetchQuery를 사용합니다.
- useQuery로 상위 페이지에서 refetch한 데이터를 가져옵니다.
> Feat[#202]: 모집 상세 페이지 api 연동

- src/components/calendar/ListBody/index.tsx
- src/components/calendar/ModalCard/ModalCard.module.scss
- src/components/calendar/ModalCard/index.tsx
- src/components/calendar/ModalContents/ModalContents.module.scss
- src/components/calendar/ModalContents/index.tsx
- src/components/calendar/index.tsx
- src/components/commons/Dropdown/Dropdown.module.scss
- src/components/commons/modals/CommonModal.module.scss
- src/components/commons/modals/CommonModal.tsx
- src/components/layout/empty/EmptyCard/EmptyCard.module.scss
- src/components/layout/empty/EmptyCard/index.tsx
- src/constants/mockData/reservationDetailMockDataConfirmed.json
- src/constants/mockData/reservationDetailMockDataDeclined.json
- src/constants/mockData/reservationDetailMockDataPending.json
- src/constants/mockData/reservationDetailMockDataPendingNoData.json
- src/constants/tapOptions.ts
- src/types/schedule.ts
- src/utils/dataMap.ts
- src/utils/getDate.ts
- issue: #99 
- close #99 
- [마이페이지] 예약현황 상세 모달 구현
- 예약 현황이 있는 날짜 클릭 시 해당 날짜에 대한 예약 현황 모달창 뜨도록 구현
- 해당 날짜에 존재하는 예약 시간들 Dropdown 으로 선택 가능하도록 구현
- 선택된 예약 시간별로 신청/거절/승인 상태의 예약 현황 리스트 표시
- commonModal 컴포넌트 사용해서 모달 UI 구현
- 신청/거절/승인 탭 별로 카드 컴포넌트 다르게 표시
- 카드 리스트가 모달창 크기를 넘어가면 스크롤되도록 구현
- 예약 내역 없으면 EmptyCard 작은버전으로 보이게 하기
- 예약 내역 2개 이상 넘어가면 스크롤 보이도록 하기
- 예약 거절/승인 버튼 누르면 confirm 모달 나오게 하기
- 예약 내역 모달창 태블릿 이하 버전에서 화면에 꽉 차게 나오도록 하기 (CommonModal 수정)
- Dropdown 선택값 길어지면 ellipse (...) 효과 적용
> Feat[#99] 마이페이지/예약현황 모달창 구현

- src/apis/queryFunctions.ts
- src/apis/queryKeys.ts
- src/components/layout/header/Header/index.tsx
- src/components/layout/header/HeaderProfile/HeaderProfile.module.scss
- src/components/layout/header/buttons/HeaderSignButton.module.scss
- src/components/layout/header/buttons/HeaderSigninButton.tsx
- src/components/layout/header/buttons/HeaderSignupButton.tsx
- src/components/layout/header/buttons/index.ts
- src/hooks/useAlarmData.ts
- src/hooks/useUserData.ts
- src/styles/mixins/_text-style.scss
- src/types/users.ts
- src/utils/checkAuth.ts
- src/utils/cookieUtils.ts
- issue: #228 
- close #228
- 비로그인 상태에 Header에 프로필 대신 보여집니다.
- Link 기능이 있습니다.
- PC 사이즈에서만 hover 효과있습니다.
- 액세스토큰이 있을 시에만 useQuery로 user data를 가져옵니다.
- 조건부로 실행되어야 하기에 hook 으로 분리했습니다.
- 액세스토큰이 있을 시에만 useQuery로 alarm data를 가져옵니다.
- 조건부로 실행되어야 하기에 hook 으로 분리했습니다.
- CSR 쿠키에서 토큰을 가져옵니다.
- SSR instance의 authorization header를 accessToken으로 설정합니다.
https://github.com/sprint-team3/GGF/assets/92169354/f8258379-d67a-4436-9ff7-965e713dc603
> Feat[#228] : Header user data와 alarm data 조회 연결

- src/apis/queryKeys.ts
- src/apis/users.ts
- src/apis/users/schema.ts
- src/components/AccountForm/index.tsx
- src/components/auth/SigninForm/index.tsx
- src/components/layout/header/Header/index.tsx
- src/stores/useUserStore.ts
- src/utils/signout.ts
- issue: #204 
- close #204
1. 프로필 초기화가 가능합니다.
2. 프로필 이미지 변경이 가능합니다.
4. 닉네임 변경이 가능합니다.
5. 프로필 이미지나 닉네임의 변경이 일어나지 않으면 저장 버튼이 활성화되지 않습니다.
6. 유저 데이터를 useUserStore에서 가져와서 보여줍니다.
1. 비밀번호 변경이 가능합니다.
2. 비밀번호 입력이 일어나지 않으면 저장 버튼이 활성화되지 않습니다.
-
> Feat[#204] : account 페이지 api 연동

- src/components/postDetail/PostDetailContent/index.tsx
- issue: #
- close #
- userStore에서 유저 데이터 참조하도록 수정했습니다.
- early return 문 삭제했습니다. 
- 조건부 렌더링 적용하여, 본인 모집글에서는 예약하기 컴포넌트 보이지 않도록 했습니다.
> Hotfix: userStore에서 유저 데이터 참조, early return 문 삭제, 조건부 렌더링 적용

- src/components/layout/Layout/index.tsx
- src/components/layout/header/Header/index.tsx
- issue: #
- close #
- 기존에 header에서 userData와 alarmData를 요청하던 것을 layout에서 하는 것으로 수정했습니다.
- 이에 따라 header의 props에 userData, alarmData, accessToken이 추가되었습니다.
> Hotfix: header api 요청 layout으로 변경

- src/apis/users/schema.ts
- src/components/AccountForm/index.tsx
- src/constants/inputNames.ts
- issue: #
- close #
- account 페이지에서 비밀번호 변경시 데이터의 키값이 다른 버그 발견하여 수정하였습니다.
- 유저 정보 수정 성공시 userData refetch 할 수 있도록 invalidateQueries 사용했습니다.
- account 페이지에서 정보 수정하면 userData참조하고 있는 header의 프로필 사진과 이미지도 바로 변경됩니다.
> Hotfix: account 비밀번호 변경시 데이터 키값 수정, 유저 정보 수정시 userData refetch

- src/components/auth/SigninForm/index.tsx
- src/components/auth/SignupForm/index.tsx
- issue: #
- close #
- signinForm, SignupForm의 로고 글씨에 Link 추가했습니다.
- AuthInputfield 그라디언트 background에 variable 사용했습니다.
> Hotfix: 로그인 회원가입 폼 로고 클릭시 랜딩으로 이동, AuthInputField background 수정

- src/apis/myActivities.ts
- src/apis/queryFunctions.ts
- src/apis/queryKeys.ts
- src/components/calendar/ModalCard/index.tsx
- src/components/calendar/ModalContents/index.tsx
- src/components/calendar/index.tsx
- src/components/commons/cards/RegisteredCard.tsx
- src/components/mypage/MyPosts/index.tsx
- src/components/mypage/ReservationStatus/index.tsx
- src/types/myActivities.ts
- src/types/schedule.ts
- issue: #135 
- close #135 
- 마이페이지의 예약 현황 페이지를 실제 API 와 연동
- 내 게시글 중 온라인/오프라인 모집 게시글만 드롭다운에 표시
- 선택된 모집 게시글에 대한 월별 예약 현황 데이터를 받아와서 달력에 표시
- 달력을 클릭하면 해당 날짜에 대한 시간별 스케줄 정보를 모달에 표시
- 모달에 스케줄 ID 별 예약 현황 표시
- pending 상태인 예약 내역에 대한 승인/거절 기능 구현
https://github.com/sprint-team3/GGF/assets/43297823/063ca1a5-482d-4c60-aee7-6497bc97fb97
-
> Feat[#135]: 마이페이지 예약 현황 API 연동

- src/components/layout/Layout/index.tsx
- src/components/layout/header/Header/index.tsx
- src/constants/initialData.ts
- src/hooks/useAlarmData.ts
- src/hooks/useUserData.ts
- src/pages/signin/index.tsx
- src/pages/signup/index.tsx
- src/stores/useUserStore.ts
- src/utils/checkAuth.ts
- src/utils/cookieUtils.ts
- src/utils/signout.ts
- issue: #
- close #
- 
1. SSR에서 비로그인 유저 토큰 갱신하여 쿠키에 저장하는 함수 구현했습니다.
2. SSR에서 로그인상태 반환해주는 함수  구현했습니다.
3. CSR에서 로그인상태 반환해주는 함수  구현했습니다.
4. 로그인 상태로 로그인 회원가입 페이지 접속시 리다이렉트 및 액세스 토큰 갱신 적용했습니다.
5. useAlarmData, useUserData 훅에서 accessToken을 파람으로 받지 않도록 수정했습니다.
6. useUserStore의 userData 타입에서 null을 삭제하고, 초기값을 객체로 만들어 넣었습니다.
> Hotfix: auth 로직 리팩토링

- src/components/layout/header/Menu/index.tsx
- issue: #
- close #
- Menu의 gameName이 없을 때 early return문을 삭제하여 버그해결했습니다.
> Hotfix: 랜딩페이지에서 Menu 게임 카테고리 이름 보이지 않는 버그 해결

- src/components/landing/Echo/index.tsx
- src/hooks/useMouseMoveEffect.ts
- issue: #
- 에코 그림자에 마우스 이동 이벤트 적용
> Hotfix: 에코 그림자에 마우스 이동 이벤트 적용

- src/components/postDetail/DefaultBanner/DefaultBanner.module.scss
- src/components/postDetail/DefaultBanner/index.tsx
- src/components/postDetail/PostDetailContent/index.tsx
- src/constants/games.ts
- src/types/games.ts
- issue: #
- close #
- 모집 유형 영어로 DeafultBanner에 추가되도록 수정했습니다.
- 이를 위해 price를 프롭으로 받도록 수정했고, 타입과 매핑 객체도 추가했습니다.
> Hotfix: DefaultBanner 리팩토링

- src/components/listPage/PostList/index.tsx
- issue: #
- close #
- 게시글 목록 상대경로를 절대경로로 수정했습니다.
- title 데이터를 splitTitleByDelimiter 유틸함수를 통해 매핑하여 card의 prop으로 내려줍니다.
> Hotfix: 게시글 목록 상대경로 수정 및 title 데이터 매핑

- src/components/createPage/PostForm/index.tsx
- src/components/editPage/EditForm/index.tsx
- issue: #
- close #
- discord maxlength 30으로 수정
- title maxlength 50으로 수정
- 이미지 업로드 후 바로 등록 버튼을 클릭 시 반영 안되는 문제 수정
- 글 수정 후 뜨는 알림 모달 문구 수정
-
-
-
-
-
> Refactor: 등록 수정 페이지 리팩토링

- src/components/landing/ClanRecruitment/ClanRecruitment.tsx
- issue: #
- close #
- 고정된 인덱스 값을 기준으로 데이터가 4개 미만일 때도 슬라이더가 이동되는 오류 해결
- 슬라이더를 이동할 수 있는 경우에만 화살표 버튼이 나타나고, 슬라이더가 이동됩니다.
- 이동이 불가능한 경우에는 버튼이 사라지며 슬라이더도 움직이지 않습니다.
https://github.com/sprint-team3/GGF/assets/77719310/6a5cb16b-e745-42d7-a4fd-2e6a2b3b75f7
> Hotfix: 랜딩 페이지-클랜 모집/슬라이더 이동 가능할 경우에만 arrow 버튼 나타나게 수정

- src/components/landing/Echo/Echo.module.scss
- src/hooks/useMouseMoveEffect.ts
- issue: #
- close #
- 에코 이미지 변경 및 에코 위치 가운데로 오도록 수정
- 에코 이미지를 1920 기준 이미지로 변경했습니다
- 기존에 에코를 `right: 0` 으로 배치하던 부분을 `pos-center-x` 로 수정했습니다
- `!important` 를 제거하고 마우스 이동 hook에서 `tanslate`에 -50%를 더해주도록 해서 에코 탈출을 막았습니다
> Hotfix: 에코 이미지 변경 및 에코 위치 가운데로 오도록 수정

- src/components/calendar/Calendar.module.scss
- src/components/calendar/index.tsx
- src/components/commons/modals/CommonModal.module.scss
- src/components/commons/modals/CommonModal.tsx
- src/components/commons/modals/CustomCommonModal.tsx
- src/components/commons/modals/index.ts
- issue: #
- close #
- [마이페이지] 예약현황 모달창 캘린더 안에서 뜨도록 수정
- react-modal 라이브러리를 사용하지 않는 CommonModal 컴포넌트 추가
- react-modal 과 비슷하게 모달창 열고닫는 애니메이션 구현
- 캘린더 모드일땐 캘린더 안에서, 리스트 모드일땐 전체화면에서 모달 열리도록 수정
> Feat: 예약 현황 모달창 수정

- src/components/landing/MatchTeam/MatchCards.tsx
- src/components/layout/Banner/index.tsx
- src/constants/images.ts
- src/pages/404/index.tsx
- src/pages/500/index.tsx
- src/pages/error/index.tsx
- src/utils/gameFormatter.ts
- issue: #
- close #
- PNGS 상수명 WEBPS로 변경
> Hotfix: PNGS 상수명 WEBPS로 변경

- src/components/auth/SigninForm/SigninForm.module.scss
- src/components/auth/SigninForm/index.tsx
- src/components/auth/SignupForm/SignupForm.module.scss
- src/components/auth/SignupForm/index.tsx
- src/components/landing/Echo/Echo.module.scss
- src/components/landing/Echo/index.tsx
- src/components/layout/Banner/Banner.module.scss
- src/components/layout/Banner/index.tsx
- src/constants/images.ts
- src/styles/mixins/_image.scss
- issue: #300 
- close #
- CSS의 background-image 속성을 사용한 큰 이미지들을 Image 태그로 대신함
- 랜딩페이지의 에코+에코그림자+배경이미지 Image 태그로 변경
- 게시글 리스트 및 게시글 등록/수정 페이지의 배너 이미지를 Image 태그로 변경
- 로그인/회원가입 페이지의 배경 이미지를 Image 태그로 변경
- Image 태그를 사용하니깐 화질이 떨어집니다. merge 하기 전에 이 브랜치를 로컬에서 받아서 한번씩 확인해보시면 좋을것 같습니다!
- [이 게시글](https://www.inflearn.com/questions/949167/next-image-%EC%A7%88%EB%AC%B8) 을 읽고 `unoptimized` 속성을 적용해보니 원본 화질로 돌아왔으나, 아무래도 최적화를 끄는 옵션이다 보니 성능상 큰 이점은 없었습니다..!
---
---
> Feat[#300]: Div 태그의 background-image 를 Image 태그로 변경

- src/components/commons/ProfileSummary/index.tsx
- src/components/commons/ProfileSummary/profileSummary.module.scss
- issue: #
- close #
- 마이페이지에서 계정관리 페이지로 이동할 수 있는 setting 아이콘을 추가했습니다.
-
-
-
-
> Refactor: 마이페이지에서 계정관리 페이지로 이동하는 아이콘 추가

- src/apis/auth.ts
- src/apis/axios.ts
- src/apis/userInstance.ts
- issue: #
- close #
1. CSR 토큰 갱신에 필요한 userInstance 생성했습니다.
2. CSR renewToken 메서드 사용시 기존 instance 대신 userInstance 사용하도록 했습니다.
3. userInstance에서 interceptor로 refreshToken을 authorization header에 첨부하도록 했습니다.
4. 기존 axios.ts의 instance에서 토큰 갱신 후 액세스토큰을 반영하기 위해 쿠키에서 토큰을 새로 꺼내와서 넣도록 수정했습니다.
> Hotfix : CSR 토큰 갱신 로직 무한 루프 버그 해결

- src/components/createPage/PostForm/index.tsx
- src/components/layout/header/Menu/index.tsx
- src/components/listPage/PostList/index.tsx
- src/pages/[game]/create/index.tsx
- src/utils/isValidGameName.ts
- issue: #
- close #
- Menu에서 게임 선택 시 리스트 페이지 url에 query를 추가하도록 수정
- 리스트 페이지에서 탭 선택 시 query가 동적으로 변하도록 수정
- 리스트 페이지에서 등록 버튼 클릭 시 현재 query 값이 등록 페이지의 url에 전달되도록 수정
- 등록 페이지에서 query의 값을 모집 유형의 기본 값으로 사용하도록 수정
- 등록 페이지의 query 값이 적절하지 않을 경우 해당 리스트 페이지로 이동시키는 로직 추가
- 적절한 query 값을 확인하는 유틸 함수 추가
-
-
-
-
-
> Refactor: 등록 페이지의 모집 유형 기본 값을 동적으로 수정

- src/components/calendar/index.tsx
- src/components/commons/modals/CustomCommonModal.tsx
- issue: #
- close #
- 예약현황 모달창 바깥 클릭시 닫히는 기능 추가
> Hotfix: 예약현황 모달창 바깥 클릭시 닫히는 기능 추가

- src/apis/myReservations/schema.ts
- src/components/postDetail/reservationPanel/Calendar/data-access/useGetScheduleList.ts
- src/components/postDetail/reservationPanel/Calendar/index.tsx
- src/components/postDetail/reservationPanel/ReservationPanel/data-access/useCreateReservation.ts
- src/components/postDetail/reservationPanel/ReservationPanel/index.tsx
- src/types/myReservations.ts
- src/utils/getDate.ts
- issue: #344 
- close #344 
- 예약하기 패널, 캘린더 리팩터링
- 선택된 달을 영문으로 변환해주는 유틸함수 적용(기존)
- 예약관련 타입 추가
- 예약관련 스키마 파일 분리
- useQuery 외부 로직으로 분리
- 불필요한 useEffect 정리
-
-
-
-
> Refactor[#344]:  예약하기 패널, 캘린더 리팩터링(react-query 로직 분리, 스키마 분리, 불필요한 useEffect 정리)
