.eslintrc.json, src/constants/apiPaths.ts, src/constants/index.ts
- issue: #2 
- apiPaths.ts 구현 및 constants/index.ts에서 export
- eslint의 "require-await": "error" 추가
- eslint의 "no-console": "warn"으로 변경
상세한 설명
-
=> feat: apiPath 구현 및 eslint 룰 수정

src/apis/activities.ts, src/types/activities.ts
- issue: 없음
- 예약 신청시 보낼 데이터 reservation 타입을 reservationBody 로 수정
상세한 설명
-
=> hotfix: 타입 이름 변경

.prettierrc.json, src/apis/auth.ts, src/apis/myActivities.ts, src/types/auth.ts, src/types/index.ts, src/types/myActivities.ts, src/utils/index.ts, src/utils/router.ts
- issue: #5 
- [기능 구현] : Auth와 MyActivities 관련 api 추상화
- [문서 업데이트] : prettier printWidth 80에서 120으로 변경
-
=> Feat[#5] : api 추상화

.eslintrc.json, .prettierignore, next.config.mjs, src/apis/activities.ts, src/apis/auth.ts, src/apis/myActivities.ts, src/apis/myNotifications.ts, src/apis/myReservations.ts, src/apis/users.ts, src/constants/index.ts, src/types/index.ts, src/types/myReservations.ts, tsconfig.json
- issue: #
- close #
- eslint import문 정렬 type과 constants 분리
- prettierignore에 md파일 추가
- scss 사용할 수 있게 next config 수정
- tsconfig @/하위 경로 삭제
- prettier printwidth 변경에 맞춰 파일들 포매팅
- auth를 type/inex.ts에 추가
-
=> Hotfix: eslint, prettierignore, next config, tsconfig 및 파일 포매팅 수정

src/apis/myReservations.ts, src/apis/users.ts, src/types/myNotifications.ts, src/types/myReservations.ts, src/types/users.ts
- issue: #26 
- close #26 
- myNotifications, myReservations, users 타입명 변경
=> Hotfix[#26]: myNotifications, myReservations, users 타입명 변경

src/apis/activities.ts, src/types/activities.ts
- issue: #
- close #
- Activities 타입명 변경
상세한 설명
-
=> hotfix: Activities 타입명 변경 및 api 객체 프로퍼티 순서 변경

package.json, src/components/commons/modal/CommonModal.module.scss, src/components/commons/modal/CommonModal.tsx, src/components/commons/modal/ConfirmModal.module.scss, src/components/commons/modal/ConfirmModal.tsx, src/components/commons/modal/ModalButton.module.scss, src/components/commons/modal/ModalButton.tsx, src/hooks/useModalState.js, src/pages/_app.tsx, src/styles/base/_globals.scss, src/styles/main.scss, src/styles/variables/_blur.scss, src/styles/variables/_colors.scss, src/styles/variables/_levels.scss, src/styles/variables/_motions.scss
- issue: #13 
- close #13 
- CommonModal 컴포넌트 구현
- ConfirmModal 컴포넌트 구현
- ModalButton 컴포넌트 구현
- useModalState 훅 생성
- keyframes 애니메이션 구현: fade-up / fade-down / glitch
👉 공통 모달 props
```js
openModal, onClose, title, renderContent
```
내부 content는 renderContent prop으로 받습니다. 
아래 예시 코드를 참고하여 컴포넌트로 만들어서 넣어주세요.
```js
<CommonModal
openModal={modalState.submitReviewModal}
onClose={() => toggleModal('submitReviewModal')}
title='리뷰 작성'
renderContent={<SubmitReview/>}
/>
```
👉 컨펌 모달 props
```js
openModal, onClose, state, title, desc, children, warning = false
```
modal 전용 버튼 컴포넌트를 children으로 넘겨줍니다.
아래 예시 코드를 참고하여 버튼 컴포넌트를 적용해 주세요.
```js
<ConfirmModal
warning
openModal={modalState.cancelReservationModal}
onClose={() => toggleModal('cancelReservationModal')}
state='STOP'
title='예약을 취소하시겠습니까?'
desc='한 번 …
```
=> Feat[#13]: 공용 모달 컴포넌트 구현, SCSS 잘못 선언된 변수 수정

.stylelintrc.json
- issue: #
- close #
- Stylelint 줄바꿈 자동 적용 rule 변경
상세한 설명
-
=> Hotfix: Stylelint 줄바꿈 자동 적용 rule 변경

package.json, src/apis/axios.ts, src/constants/auth.ts
- issue: #4 
- close #
- withCredentials: false 추가
- 아래처럼 intercepter request 설정
1. accessToken이 없고, refreshToken만 있을 때는 토큰을 갱신해서 쿠키에 저장
2. accessToken이 있을 때는 headers authorization에 bearer로 첨부
-
=> Feat[#4] : axios instance 구현

src/components/commons/modal/CommonModal.tsx, src/components/commons/modal/ConfirmModal.tsx, src/components/commons/modal/ModalButton.tsx, src/components/commons/modal/index.ts, src/hooks/useModalState.ts, tsconfig.json
- issue: #
- close #
- tsconfig 파일을 수정하여 JavaScript 파일을 허용하지 않도록 규칙 변경
- useModalState 훅 파일의 확장자를 .ts로 변경하고 타입 명시
- modal 폴더 내의 모든 컴포넌트를 index.js 파일에서 export 변경
- onClose 이벤트 핸들러의 타입 수정
=> Hotfix: 공통 모달 export 수정 및 tsconfig 규칙 변경

.eslintrc.json, .storybook/main.ts, .storybook/preview.ts, package-lock.json, package.json, src/components/commons/buttons/BaseButton.module.scss, src/components/commons/buttons/BaseButton.tsx, src/components/commons/buttons/index.ts, src/components/commons/modal/ConfirmModal.module.scss, src/stories/Badge.stories.ts, src/stories/BaseButton.stories.ts, src/stories/CommonModal.stories.ts, src/stories/ConfirmModal.stories.ts, src/stories/ModalButton.stories.ts, src/stories/Tag.stories.ts, src/styles/mixins/_text-style.scss, src/styles/variables/_colors.scss
- issue: #11
- close #
- 공용 버튼 컴포넌트 중, 일반 버튼 컴포넌트 구현
- 프로젝트에 스토리북 도입
- 노션에 버튼 컴포넌트랑 스토리북 사용 방법 적어놓겠습니다!
- 버튼컴포넌트: 공용 컴포넌트 사용법
- 스토리북: 데브위키
- 리뷰 반영사항
- color variable, font style mixin 추가
- [기존] theme 프롭을 넘기지 않으면 outline테마가 자동 적용 -> [변경 후] theme 프롭을 꼭 넘겨주어야 함
-
=> Feat: 일반 버튼 컴포넌트 구현 + 스토리북 도입

src/components/commons/buttons/BaseButton.module.scss
- issue: #
- close #
- BaseButton 컴포넌트 스타일 오류 수정
- Ghost 버튼의 배경색이 적용되지 않는 문제 해결
- border 테스트를 위해 바꿨던 코드 원상복구
-
=> hotfix: 버튼 스타일 오류 수정

.storybook/main.ts, src/stories/Alarm.stories.ts, src/stories/Avatar.stories.ts, src/stories/ReviewCard.stories.ts, src/stories/StarRating.stories.ts, src/types/index.ts
- issue: #
- close #
- 지금까지 구현된 공용 컴포넌트들에 대한 story 추가
상세한 설명
-
=> Feat: 공용 컴포넌트 story 추가

package.json
- issue: #
- close #
- package.json에서 react hook form 라이브러리 중복코드가 있어서 삭제했습니다.
-
=> Chore: react hook form 중복 코드 삭제

src/components/commons/InputField/index.tsx
- issue: #
- close #
-  isErrorVisible이 true일 때만 에러메시지가 보이도록 수정했습니다.
상세한 설명
-
=> Refactor: isErrorVisible이 true일 때만 에러메시지가 보이도록 수정

src/components/commons/buttons/BaseButton.tsx, src/components/commons/buttons/OperationButton.tsx
- issue: #
- close #
- Prop 네임들 중 disabled 를 isDisabled 로 수정
상세한 설명
-
=> Hotfix: 컨벤션에 맞게 프로퍼티명 수정

.gitignore, package-lock.json
- issue: #
- close #
- package-lock.json 추가했습니다.
- gitignore에서 packge-lock.json 삭제했습니다.
=> HotFix: package-lock.json 추가, gitignore 수정

src/components/commons/InputField/InputField.module.scss, src/styles/variables/_colors.scss
- issue: #
- close #
- scss에 있는 variable을 사용해 background 변경했습니다.
=> Hotfix: InputField의 background를 $input-background로 변경

src/components/commons/buttons/index.ts, src/stories/ArrowButton.stories.ts, src/stories/BaseButton.stories.ts, src/stories/CountButton.stories.ts, src/stories/MoreButton.stories.ts, src/stories/OperationButton.stories.ts
- issue: #11 
- close #
- 버튼 컴포넌트를 다 만들어놓고 index.ts 에서 export 하는걸 깜빡해서, 지금 한번에 추가해놨습니다
상세한 설명
-
=> Hotfix[#11]: 공용 버튼 컴포넌트들 buttons 폴더의 index.ts에 export 추가

src/components/commons/StarRating/index.tsx
- issue: #64 
- close #64 
- 불필요한 useEffect 삭제
- 필수 props로 rating을 받아서 state 적용
- 
-
=> Refactor[#64]: 별점 필수 props 변경 및 useEffect 삭제

src/components/commons/Tab/Tab.module.scss, src/components/commons/Tab/index.tsx, src/stories/Tab.stories.ts
- issue: #20 
- close #20 
- Tab 컴포넌트 구현
[필수]
- **items:** 탭을 구성할 아이템 객체의 배열을 지정
- id: 각 아이템의 id
- text: 탭에 표시할 텍스트
- count: 텍스트 옆에 표시할 숫자값 (옵셔널)
- **size:** 버튼 사이즈 지정
- small / medium
- **selectedTabId:** 선택된 탭 아이템의 아이디
- 외부에서 state 값으로 넣어줘야 함
- items로 넘겨준 id들 중 하나를 초기값으로 설정해서 넘겨줄 것!
- **setSelectedTabId**: 탭을 눌렀을 때 setSelectedTabId를 변경시켜줄 setState 함수
- 외부에서 state를 선언할때 같이 선언했던 setState 함수를 넣어줄것!
- 카운트 없는 탭  (medium 사이즈)
```tsx
const items = [
{ id: 'total', text: '전체' },
{ id: 'myPost', name: '등록한 게시글' },
{ id: 'myReservation', text: '신청한 예약' },
];
const [selectedItem, setSelectedItem] = useState(items[0].id);
<Tab items={items} size='medium' selectedTabId={selectedItem} setSelectedTabId={setSelectedItem} />
```
- 카운트 있는 탭 (small 사이즈)
```tsx
const items = [
{ id: 'pending', text: '신청', …
```
=> Feat[#20]: 공용 탭 컴포넌트 구현

src/stories/Alarm.stories.ts, src/stories/Avatar.stories.ts, src/stories/Badge.stories.ts, src/stories/ReviewCard.stories.ts, src/stories/Tab.stories.ts, src/stories/Tag.stories.ts
- issue: #
- close #
- 스토리북 컴포넌트별 그룹 추가
- Alarm + Avatar -> Profile 그룹에 추가
- Badge + Tag -> Badge&Tag 그룹에 추가
- Tab + Filter -> Tab&Filter 그룹에 추가
- ReviewCard -> Cards 그룹에 추가
-
=> Refactor: 스토리북 컴포넌트 그룹 추가

src/components/commons/buttons/ArrowButton.module.scss, src/components/commons/buttons/ArrowButton.tsx, src/components/commons/buttons/BaseButton.module.scss, src/components/commons/buttons/BaseButton.tsx, src/components/commons/buttons/CountButton.module.scss, src/components/commons/buttons/CountButton.tsx, src/components/commons/buttons/MoreButton.module.scss, src/components/commons/buttons/MoreButton.tsx, src/components/commons/buttons/OperationButton.module.scss, src/components/commons/buttons/OperationButton.tsx
- issue: #
- close #
- [전체] Image 태그에 width, height 속성 넣고 불필요한 div 태그 제거
- [전체] 버튼 클래스명을 더 구체적으로 수정
- [CountButton] 한줄 if문에 중괄호 추가
- [BaseButton] 불필요한 스타일 구문 제거
- [BaseButton] scss 중첩 구문 수정
상세한 설명
-
=> Refactor: 버튼 컴포넌트 tsx, scss 컨벤션에 맞게 수정 및 리팩터링

src/components/layout/Footer/Footer.module.scss, src/components/layout/Footer/index.tsx, src/stories/Footer.stories.ts
- issue: #22 
- close #22 
- 공용 레이아웃 중 Footer 컴포넌트 구현
-
=> Feat[#22]: Footer 컴포넌트 구현

src/components/commons/Kebabmenu/Kebabmenu.module.scss, src/components/commons/Kebabmenu/index.tsx, src/stories/Kebabmenu.stories.ts
- issue: #83 
- close #83
- setState를 prop으로 받아 클릭한 li 내용을 전달해줍니다.
자세한 UI는 스토리북에서 확인 가능합니다.
-
=> Feat[#83]: 공통 Kebabmenu 구현

src/components/commons/Kebabmenu/Kebabmenu.module.scss, src/components/commons/Kebabmenu/index.tsx
- issue: #
- close #
- CSS 버그 수정 및 useTogglePopup 적용했습니다.
상세한 설명
-
=> HotFIx: Kebabmenu 리팩토링

src/components/commons/Filter/Filter.module.scss, src/components/commons/Filter/index.tsx, src/stories/Filter.stories.ts
- issue: #21 
- close #21 
- 공용 필터 컴포넌트 구현
탭 컴포넌트와 사용법은 거의 유사합니다
[필수]
- **items:** 필터를 구성할 아이템 객체의 배열을 지정
- id: 각 아이템의 id
- text: 필터에 표시할 텍스트
- **selectedFilterId:** 선택된 필터 아이템의 아이디
- 외부에서 state 값으로 넣어줘야 함
- items로 넘겨준 id들 중 하나를 초기값으로 설정해서 넘겨줄 것!
- **setSelectedFilterI**: 필터를 눌렀을 때 setSelectedFilterId를 변경시켜줄 setState 함수
- 외부에서 state를 선언할때 같이 선언했던 setState 함수를 넣어줄것!
✅ import
```tsx
import Filter from '@/components/commons/Filter';
```
✅ 사용법
```tsx
const items = [
{ id: 'total', text: '전체' },
{ id: 'lol', text: '리그오브레전드' },
{ id: 'pubg', text: '배틀그라운드' },
{ id: 'overwatch', text: '오버워치 2' },
{ id: 'minecraft', text: '마인크래프트' },
];
const [selectedItem, setSelectedItem] = useState(items[0].id);
<Filter items={items} selectedFilterId={selectedItem} setSelectedFilterId={setSelectedItem} />
``` …
=> Feat[#21]: 공용 필터 컴포넌트 구현

src/components/commons/Kebabmenu/index.tsx, src/components/commons/cards/CardCommonStyle.module.scss, src/components/commons/cards/RegisteredCard.tsx, src/stories/RegisteredCard.stories.ts
- issue: #94 
- close #94 
- 케밥 컴포넌트 추가 및 props 수정
- value에 따른 모달 연동 및 페이지 이동 로직 추가
상세한 설명
https://github.com/sprint-team3/GGF/assets/77719310/4765b51e-4baa-4d19-85c6-589552967758
- 사용하시는 분이 redirect 설정해 주셔야 합니다.
- 수정 버튼 클릭 시 권한 확인 및 예약 status 확인 로직이 필요합니다.
=> Refactor[#94]: 등록한 모집 카드 컴포넌트 리팩토링(케밥 메뉴 및 모달 연결)

src/components/commons/inputs/Dropdown.module.scss, src/components/commons/inputs/Dropdown.tsx, src/styles/mixins/_scrollbar.scss
- issue: #
- close #
- Dropdown 컴포넌트 스크롤바 CSS 수정했습니다.
상세한 설명
-
=> HotFix: dropdown 스크롤바 수정

src/components/commons/ReviewCard/index.tsx, src/components/commons/StarRating/index.tsx
- issue: #
- close #
- map index 수정했습니다. 
상세한 설명
-
=> Hotfix: idx -> index 수정

src/components/commons/cards/ReservedCard.tsx, src/utils/getDate.ts
- issue: #
- close #
- boolean을 반환하는 함수로 명칭을 변경하였습니다.
- getExpirationDate 👉 isExpirationDate
상세한 설명
-
=> Hotfix: getExpirationDate 함수 이름 변경

src/components/commons/StarRating/index.tsx
- issue: #
- close #
- readonly 고정값 false로 변경하였습니다.
상세한 설명
-
=> Hotfix: StarRating 컴포넌트 readonly 고정값 false로 변경

src/styles/base/_reset.scss
- issue: #
- close #
- 전체 body 영역에  min-height: 100vh 속성 추가했습니다.
상세한 설명
-
=> Hotfix: body min-height: 100vh 속성 추가

src/components/commons/ProfileSummary/index.tsx, src/components/commons/ProfileSummary/profileSummary.module.scss, src/stories/ProfileSummary.stories.ts
- issue: #115 
- close #115 
- [UI 구현] 컴포넌트 반응형 UI 구현
- 쿼리에서 받아온 totalCount를 각 recruitmentTotalCount, reservationTotalCount 변환해서 내려주어야 합니다.
```ts
type ProfileSummaryProps = {
nickname: string;
email: string;
profileImageUrl: string | null;
recruitmentTotalCount: number;
reservationTotalCount: number;
};
```
-
=> Feat[#115]: 마이페이지 profileSummary 컴포넌트 구현

src/components/commons/Filter/index.tsx
- issue: #113 
- close #113 
- 멘토링 리뷰 반영
- Filter 컴포넌트의 부정 조건문을 early return 문으로 변경
상세한 설명
-
=> Refactor[#113]: Filter 컴포넌트의 부정 조건문을 early return 문으로 변경

src/components/commons/modals/CommonModal.module.scss, src/components/commons/modals/CommonModal.tsx, src/components/commons/modals/ConfirmModal.tsx, src/stories/ConfirmModal.stories.ts, src/styles/variables/_blur.scss
- issue: #123 
- close #123 
- 공용 Modal 컴포넌트 리팩토링
- children props -> renderButton props 수정되었습니다.
- 아래 코드와 같이 사용해 주세요.
```js
<ConfirmModal
warning
openModal={multiState.cancelReservationModal}
onClose={() => handleCommonModal('cancelReservationModal')}
state='STOP'
title='예약을 취소하시겠습니까?'
desc='한 번 취소한 예약은 되돌릴 수 없습니다'
renderButton={
<>
<ModalButton variant='warning' onClick={() => handleCommonModal('cancelReservationModal')}>
예약 취소
</ModalButton>
<ModalButton onClick={() => handleCommonModal('cancelReservationModal')}>닫기</ModalButton>
</>
}
/>
```
상세한 설명
-
=> Refactor[#123]: 공용 Modal 컴포넌트 리팩토링

src/hooks/useSignin.ts
- issue: #53 
- close #53 
- 기존 try catch 문대신 onSuccess와 onError를 사용했습니다.
- 아직 에러 처리 방법은 정해지지 않아 console.error로 두었습니다.
- error message를 schema의 에러메시지로 설정하면 좋을 것 같아서 error를 반환하도록 하였습니다.
상세한 설명
1. onError에서 어떻게 에러 처리하는 게 좋을까요?
=> Refactor[#53]: useSignin 리팩토링

src/components/commons/inputs/Dropdown.tsx
- issue: #102 
- close #102
- props 중 setState를 onChange 함수로 바꾸어 드롭다운 옵션의 title과 value를 넘기도록 했습니다.
- 복잡한 조건문과 타입 체크문을 삭제하였습니다.
상세한 설명
-
=> refactor[#102]: Dropdown 리팩토링

src/hooks/useSignin.ts
- issue: #
- close #
- 리팩토링 없이 실수로 useSignin을 머지시켜서 핫픽스 올립니다.
-
-
-
-
-
=> Hotfix: onError 삭제

src/components/commons/Avatar/Avatar.module.scss, src/components/commons/Avatar/index.tsx, src/components/commons/ProfileSummary/index.tsx, src/components/commons/ReviewCard/index.tsx, src/components/layout/header/Alarm/Alarm.module.scss, src/components/layout/header/Alarm/index.tsx, src/components/layout/header/AlarmCard/AlarmCard.module.scss, src/components/layout/header/AlarmCard/index.tsx, src/components/layout/header/AlarmList/AlarmList.module.scss, src/components/layout/header/AlarmList/index.tsx, src/components/layout/header/DrawerMenu/index.tsx, src/components/layout/header/Header/index.tsx, src/components/layout/header/HeaderProfile/HeaderProfile.module.scss, src/components/layout/header/HeaderProfile/index.tsx, src/components/layout/header/Menu/Menu.module.scss, src/components/layout/header/Menu/index.tsx, src/components/layout/header/UserMenu/UserMenu.module.scss, src/components/layout/header/UserMenu/index.tsx, src/stories/Alarm.stories.ts, src/stories/AlarmCard.stories.ts, src/stories/AlarmList.stories.ts, src/stories/Avatar.stories.ts, src/stories/DrawerMenu.stories.ts, src/stories/HeaderProfile.stories.ts, src/stories/Menu.stories.ts, src/stories/UserMenu.stories.ts
- issue: #120 
- close #120 
-
=> Refactor[#120] : Header에서 사용되는 컴포넌트들 리팩토링

src/components/commons/inputs/ImageField.tsx
- issue: #
- close #
- ConfirmModal의 renderButton props 추가에 따라 변경하였습니다.
-
-
-
-
-
=> Hotfix: confirmModal renderButton 변경에 따른 수정

src/components/commons/cards/RegisteredCard.tsx, src/components/commons/cards/ReservedCard.tsx
- issue: #
- close #
- Confirm모달 사용하는 곳에서 버튼 넣는 방법 수정
- children -> renderButton
-
-
-
-
-
=> Hotfix: Confirm모달 사용처에서 Button 넣는법 수정

src/types/myActivities.ts, src/types/myReservations.ts, src/types/users.ts
- issue: #
- close #
- 유저 타입, 예약 상태 타입 추가 및 리팩터링
-
-
-
-
-
=> Hotfix: 타입 정의 리팩토링

src/components/layout/header/Header/Header.module.scss, src/components/layout/header/Header/index.tsx
- issue: #
- close #
-
-
-
-
-
=> Hotfix : Header 컴포넌트 fixed 속성 적용

src/constants/games.ts, src/constants/myReservationsStatus.ts, src/constants/postTypes.ts, src/types/games.ts, src/types/myReservations.ts
- issue: #
- close #
- 멘토링 피드백 반영
- types에서는 단순 유니온 타입만 정의하고 constants에서만 단방향으로 type을 임포트하도록 수정
- as const 를 쓰지 않고, Record로 명확하게 타입 정의
- 불필요한 객체 제거
- 기존 api 의 카테고리명 (스포츠, 투어 등) 과 게임명을 매칭하는 객체 추가
- 기존 api의 price 와 게시글 타입을 매칭하는 객체 추가
-
-
-
-
-
=> Refactor: 타입 정의 추가 및 수정

next.config.mjs, src/components/layout/Footer/Footer.module.scss, src/components/layout/FullLayout/FullLayout.module.scss, src/components/layout/FullLayout/index.tsx, src/components/layout/Layout/Layout.module.scss, src/components/layout/Layout/index.tsx, src/components/layout/empty/EmptyLayout/index.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/landing/index.tsx, src/pages/signin/index.tsx, src/pages/signup/index.tsx, src/styles/base/_reset.scss, src/styles/mixins/_scrollbar.scss
- issue: #142 
- close #142 
- FullLayout 컴포넌트 구현
- Layout 컴포넌트 구현
- SCSS : body-scrollbar 추가
- 루트 페이지 경로 변경: /landing
- FullLayout : footer 컴포넌트 포함되어 있습니다. 기본 layout입니다.
- Layout : Header 컴포넌트 포함되어 있습니다.
- 로그인, 회원가입 페이지는 FullLayout 기본값 사용합니다.
- 이 외의 다른 페이지는 사용하기 참고하셔서 하단에 Layout을 선언해서 사용합니다.
```js
export default function App({ Component, pageProps }: AppProps) {
const Layout = (Component as ComponentType).FullLayout || EmptyLayout;
return (
<QueryClientProvider client={queryClient}>
<ReactQueryDevtools initialIsOpen={false} />
<FullLayout>
<Layout>
<Component {...pageProps} />
</Layout>
</FullLayout>
</QueryClientProvider>
);
}
```
-
-
- landingPage
```js
import Layout from '@/components/layout/Layout';
const LandingPage = () => {
return <div>LandingPage</div>;
};
export default …
```
=> Feat[#142]: 공용 layout 컴포넌트 구현 및 페이지 적용

src/components/layout/header/DrawerMenu/DrawerMenu.module.scss, src/components/layout/header/DrawerMenu/index.tsx, src/components/layout/header/Header/Header.module.scss, src/components/layout/header/Header/index.tsx, src/components/layout/header/Menu/index.tsx, src/stories/DrawerMenu.stories.ts
- issue: #
- close #
- Header 컴포넌트 : container 삭제, header 태그 적용, 
DrawerMenu 컴포넌트를 state를 이용하지 않고 렌더링하도록 수정,
DrawerMenu 컴포넌트가 슬라이딩 형식으로 나타나고 사라지도록 하면서 최초 렌더링 시에는 해당 효과가 적용되지 않도록 수정
- Drawer 컴포넌트 : state를 이용하여 toggle하던 부분을 삭제하고 close button을 이용하여 닫히도록 수정
- Menu 컴포넌트 : 초기값이 지정되어 있던 부분을 삭제
-
-
-
-
-
=> Hotfix: Header & Menu & DrawerMenu 리팩토링

README.md
- issue: #
- close #
- 현기님 이름 쿠키맛 개발자로 수정
-
-
-
-
-
=> Hotfix: README.md 현기님 닉네임 수정

src/components/layout/header/Header/Header.module.scss
- issue: #
- close #
- DrawerMenu 위치 수정
-
-
-
-
-
=> Hotfix: DrawerMenu 위치 수정

src/components/layout/header/Header/Header.module.scss, src/components/layout/header/Header/index.tsx
- issue: #
- close #
Header에서 useDeviceType 커스텀 훅 사용
-
-
-
-
-
=> Hotfix; Header에서 useDeviceType 커스텀 훅 사용

src/components/commons/Tab/index.tsx, src/stories/Tab.stories.ts
- issue: #
- close #
-
-
-
-
-
-
=> Hotfix: Tab 컴포넌트 export default 수정

src/components/commons/buttons/BaseButton.tsx
- issue: #
- close #
- BaseButton에 type 프로퍼티 추가
-
-
-
-
-
=> Hotfix: BaseButton에 type 추가

src/components/commons/Filter/Filter.module.scss, src/stories/Filter.stories.ts
- issue: #
- close #
- 각 필터 버튼의 border를 box-shadow로 변경
-
-
-
-
-
=> Hotfix: 필터 리스트 모바일에서 잘리는 오류 해결

src/components/commons/Dropdown/Dropdown.module.scss, src/components/commons/Dropdown/index.tsx, src/components/commons/inputs/FormDropdown.module.scss
- issue: #
- close #
- 리스트 overflow 버그 해결했습니다.
- focus시 $primary 컬러도 쓸 수 있게 color 프롭 추가했습니다.
- 리스트 overflow 버그 해결했습니다.
=> Hotfix: FormDropdown css 수정, Dropdown 컬러 프롭 추가

src/styles/base/_reset.scss
- issue: #
- close #
- 모달 열릴 때 스크롤바 없어지면서 body 줄어드는 현상 수정했습니다.
=> Hotfix: body 고정 스크롤바 영역 지정, html 스크롤바 유지되는 속성 추가

src/components/mypage/MypageContent/index.tsx
- issue: #
- close #
- 선언된 tabContentMap 객체를 마이페이지 컴포넌트 외부로 분리했습니다.
=> Hotfix: tabContentMap 객체 분리

src/components/commons/StarRating/index.tsx
- issue: #
- close #
- onChange prop을 받아서 상위 form 요소에 올려줄 rating 값을 설정하였습니다
=> Hotfix: onChange prop 추가

src/components/commons/inputs/TextField.module.scss, src/components/commons/inputs/TextField.tsx, src/styles/mixins/_scrollbar.scss
- issue: #
- close #
- TextField라벨없을시 라벨 영역 삭제, thick scrollbar 디자인 수정했습니다.
-
-
-
-
-
=> Hotfix: TextField라벨없을시 라벨 영역 삭제, thick scrollbar 디자인 수정

src/components/commons/inputs/FormDropdown.tsx
- issue: #
- close #
- options의 value가 string도 받을 수 있게 타입 수정했습니다.
=> Hotfix: options의 value가 string도 받을 수 있게 타입 수정

src/components/commons/inputs/InputField.module.scss, src/components/commons/inputs/InputField.tsx, src/components/commons/inputs/TextField.module.scss
- issue: #
- close #
- inputfield 고정 height 삭제하고, error message bottom -2 rem으로 변경했습니다.
- password 타입일 때만 오른쪽 padding 주도록 변경했습니다.
- textfield placeholder 스타일 추가했습니다.
=> Hotfix: inputfield textfield 수정

src/components/commons/Filter/index.tsx, src/constants/games.ts, src/hooks/useFilteredDataList.ts, src/utils/formatGameToLink.ts, src/utils/gameFormatter.ts, src/utils/index.ts
- issue: #
- close #
- 필터 컴포넌트의 이벤트 핸들러를 일반 화살표함수로 변경
- 함수 인자로 선택된 필터ID를 받을수 있도록 함
- 데이터 필터링 커스텀훅에서, selectFilter 의 키 중 값이 'all'인 것이 있으면 해당 키에 대해서 필터링을 수행하지 않도록 수정
- 기존 api의 카테고리를 게임명으로 변환하는 유틸함수 추가
-
-
-
-
-
=> Hotfix: 필터 컴포넌트 + 필터링 커스텀훅 수정

src/types/sort.ts
- issue: #
- close #
- 정렬할 때의 'asc' | 'desc' 타입을 따로 타입 변수로 분리
-
-
-
-
-
=> Hotfix: 정렬 관련 타입 추가

src/components/layout/empty/EmptyCard/EmptyCard.module.scss
- issue: #
- close #
- EmptyCard 에 border-radius 추가
-
-
-
-
-
=> Hotfix: EmptyCard에 border radius 추가

src/components/commons/Dropdown/Dropdown.module.scss, src/components/commons/Dropdown/index.tsx, src/components/commons/Kebabmenu/Kebabmenu.module.scss
- issue: #
- close #
- kebabmenu 리스트 z-index와 box-shadow 추가
- dropdown 리스트 cursor와 transition 추가
- dropdown onChange 파람 title 삭제, value 타입 string | number로 변경
=> Hotfix: KebabMenu css 수정, Dropdown 타입 및 css 수정

src/components/commons/inputs/TextField.tsx
- issue: #
- close #
- `watch(name)`으로 변경하였습니다.
=> Hotfix: TextField 실시간 글자수 반영 안 되는 버그 해결

src/components/commons/buttons/BaseButton.module.scss
- issue: #
- close #
- 베이스버튼 disabled일때 호버되는 오류 해결
=> Hotfix: 베이스버튼 disabled일때 호버되는 오류 해결

src/types/activities.ts, src/types/index.ts, src/types/schedule.ts
- issue: #
- close #
- 스케줄 관련 타입 파일을 따로 분리
=> Hotfix: 스케줄 타입 따로 분리

src/components/commons/Pagination/index.tsx
- issue: #
- close #
- 페이지네이션 ul 에 li 태그 추가
- 페이지네이션 nav에 role 추가
=> Hotfix: 페이지네이션 ul 에 li 태그 추가

src/hooks/useDeviceType.ts
- issue: #
- close #
- `ReviewList`에서 이 훅을 사용하는 `Pagination`에서 `hydration error`가 발생하여
- `useDeviceType` 훅에서 사용하는 `useState`의 초기값에서 `window` 객체를 참조하는 부분을 수정했습니다.
=> Hotfix: useDeviceType의 useState 초기값 수정

src/components/postCreate/PostForm/index.tsx
- issue: #
- close #
-
-
-
-
-
=> Hotfix: description에 discord 항목 추가

src/components/postDetail/reservationPanel/ReservationPanel/index.tsx
- issue: #
- close #
- 상세페이지의 post type이 오프라인일 경우 모달 버튼이 보이지 않아 variant=success 속성을 추가하였습니다.
- 누락된 isNoSchedule를 dependency array에 추가하였습니다.
=> Hotfix: 모달 버튼 컴포넌트 variant 속성 추가, 누락된 dependency 추가

src/components/commons/Avatar/Avatar.module.scss, src/components/commons/Avatar/index.tsx, src/components/createPage/PostForm/PostForm.module.scss, src/components/createPage/PostForm/index.tsx, src/components/layout/header/AlarmList/AlarmList.module.scss, src/components/layout/header/DrawerMenu/index.tsx, src/components/layout/header/Header/Header.module.scss, src/components/layout/header/Header/index.tsx, src/components/layout/header/Menu/index.tsx, src/components/layout/header/UserMenu/index.tsx, src/components/listPage/PostList/index.tsx, src/constants/pagePaths.ts, src/utils/router.ts
- issue: #207 
- close #207 
`[Alarm]` `[UserMenu]` 
`[UserMenu]` 
`[Logo]` 
`[Avatar]` 
`[DrawerMenu]` 
`[모집 등록 페이지]` 
-
-
-
-
-
=> Refactor[#207] : Header 관련 컴포넌트들 리팩토링

src/components/commons/modals/ConfirmModal.module.scss, src/components/commons/modals/ModalButton.module.scss
- issue: #
- close #
- PC를 제외한 디바이스의 hover 속성을 제거하였습니다.
- 모달 버튼의 텍스트 컬러를 $gray10으로 변경하여 가독성을 높였습니다.
=> Hotfix: 태블릿, 모바일 디바이스에서 hover 속성 제거 및 모달 버튼 텍스트 컬러 변경

src/components/commons/ProfileSummary/profileSummary.module.scss
- issue: #
- close #
- 모집 등록과 카운트 정렬이 맞지 않아 flexbox mixin을 활용하여 정렬을 조정했습니다.
=> Refactor: profileSummary 정렬 속성 추가

src/components/commons/Avatar/index.tsx
- issue: #
- close #
- 기본 프로필 이미지일 때 클레스네임 삭제
-
-
-
-
-
=> Hotfix: 기본 프로필 이미지 클래스네임 삭제

src/apis/queryFunctions.ts, src/apis/queryKeys.ts, src/constants/pagePaths.ts, src/pages/mypage/index.tsx
- issue: #
- close #
- queryKeys.ts 파일
- queryFunctions.ts 파일
- PAGE_PATHS -> landing 추가
- 리액트 쿼리 SSR 적용
- 노션 참고
https://www.notion.so/SSR-React-Query-a521030dfea74ab6ad76d9f97eca6bd0
=> Hotfix: queryKeys, queryFunctions 파일 생성 및 리액트 쿼리 SSR 적용

src/components/createPage/PostForm/index.tsx, src/constants/postForm.ts, src/utils/gameFormatter.ts
- issue: #219 
- close #219 
-
-
-
-
-
=> Refactor[#219] : 모집 등록 기능 추가

src/apis/myReservations.ts, src/hooks/useFilteredDataList.ts
- issue: #
- close #
- 내 예약 리스트 조회 API 매개변수 삭제
- 필터 시 초기 데이터 값이 있을 경우에만 실행되도록 조건문 추가
=> Hotfix: 내 예약 리스트 조회 API 추상화 수정, 초기 데이터 값이 있을 경우에만 실행되도록 조건문 추가

src/components/commons/Pagination/Pagination.module.scss, src/components/commons/cards/CardCommonStyle.module.scss
- issue: #
- close #
- 등록한 게시글 카드 컴포넌트 hover 효과 PC에만 적용
- 페이지네이션 hover 효과 PC에만 적용
-
-
-
-
-
=> Hotfix: 등록한 게시글 카드 컴포넌트, 페이지네이션 Hover 수정

src/apis/activities.ts, src/apis/queryFunctions.ts, src/apis/queryKeys.ts, src/components/listPage/ListPageContent/index.tsx, src/components/listPage/PostList/index.tsx, src/pages/[game]/index.tsx, src/types/myActivities.ts
- issue: #231 
- close #231 
- 리스트 페이지 API 연동
-
-
-
-
-
=> Feat[#231] 리스트 페이지 API 연동

src/apis/activities.ts, src/components/createPage/CreatePageContent/index.tsx, src/components/createPage/PostForm/index.tsx, src/pages/[game]/create/index.tsx, src/utils/postFormUtils.ts
- issue: #233 
- close #233 
-
-
-
-
-
=> Feat[#233]: 등록 페이지 API 연동

src/apis/activities.ts, src/components/createPage/PostForm/index.tsx
- issue: #254 
- close #254 
- PostForm 이미지 등록 기능 수정
-
-
-
-
-
=> Refactor[#254]: PostForm 이미지 등록 기능 수정

src/apis/queryKeys.ts, src/components/commons/ProfileSummary/index.tsx, src/components/mypage/MypageContent/index.tsx, src/pages/mypage/index.tsx
- issue: #251 
- close #251 
- ProfileSummary 컴포넌트 API 연동
- userData API연결 및 데이터 적용
- 등록한 게시글, 신청한 예약 API 연결 및 총 Count 데이터 적용
```js
const email = userData?.email;
const nickname = userData?.nickname;
const profileImage = userData?.profileImageUrl;
const recruitmentTotalCount = myPosts?.length;
const reservationTotalCount = myReservations?.length;
```
```js
<ProfileSummary
nickname={nickname}
email={email}
profileImageUrl={profileImage}
recruitmentTotalCount={recruitmentTotalCount}
reservationTotalCount={reservationTotalCount}
/>
```
=> Feat[#251]: ProfileSummary 컴포넌트 API 연동

src/pages/account/index.tsx, src/pages/mypage/index.tsx, src/utils/checkAuth.ts
- issue: #
<!-- 작업한 내용을 카테고리와 함께 설명해주세요
ex) - [UI 구현] 간결하게 작성 
- requiresLogin : 토큰 파람으로 받지 않고, 자체적으로 쿠키에서 꺼내오고, 갱신한 토큰 쿠키에 넣도록 리팩토링했습니다.
- 사용하는 페이지 부분도 수정했습니다.
=> Hotfix :  requiresLogin 리팩토링 및 requiresLogin 사용하는 account, mypage 수정

src/components/layout/header/Menu/Menu.module.scss, src/components/layout/header/buttons/HeaderSignButton.module.scss
- issue: #
- close #
- 태블릿 사이즈에서 헤더 메뉴가 영역 밖으로 튀어나오지 않게 사이즈 변경하였습니다.
=> Hotfix: 헤더 컴포넌트 메뉴, 로그인 버튼, 회원가입 버튼 반응형 적용

src/components/mypage/MyPosts/index.tsx, src/components/mypage/ReservationStatus/index.tsx, src/constants/pagePaths.ts
- issue: #
- close #
- 등록한 게시글 없을때 예약현황 탭 undefined 오류 수정
- 게시글 수정 클릭시 이동할 링크 수정
=> Hotfix: 마이페이지 오류 수정

src/components/calendar/ModalContents/ModalContents.module.scss
- issue: #
- close #
- 태블릿 이하 사이즈에서 남은 비율에 맞춰 영역을 차지하도록 max-height 재설정
=> Hotfix: 캘린더 모달 컨텐츠 max-height 재설정

src/components/layout/header/UserMenu/index.tsx, src/utils/router.ts
- issue: #
- close #
- 로그아웃 클릭 시 페이지 새로고침 로직 추가
-
-
-
-
-
=> Refactor: UserMenu 로그아웃 클릭 시 페이지 새로고침 로직 추가

src/components/createPage/PostForm/index.tsx, src/constants/index.ts, src/constants/queryClient.ts, src/pages/[game]/create/index.tsx, src/pages/[game]/edit/[activityId]/index.tsx, src/utils/queryClient.ts
- issue: #
- close #
- 등록 및 수정 페이지에 requiresLogin 유틸 적용
- queryClient에서 staleTime 제거
- staleTime 값이 저장된 constants 폴더의 queryClient 파일 삭제
-
-
-
-
-
=> Refactor: 등록 및 수정 페이지 리팩토링

src/components/postDetail/reservationPanel/ReservationPanel/index.tsx
- issue: #
- close #
- stale Time 변경으로 필요없는 리패칭 로직 삭제했습니다.
=> Hotfix: stale Time 변경으로 필요없는 리패칭 로직 삭제

src/components/postDetail/PostDetailContent/index.tsx, src/components/postDetail/ReviewList/index.tsx, src/components/postDetail/ReviewSummary/index.tsx, src/pages/[game]/[postId]/index.tsx
- issue: #
- close #
- ReviewSummary에서 글쓴이 정보를 보여주도록 수정했습니다.
=> Hotfix: ReviewSummary에서 글쓴이 정보 보여주도록 수정

src/components/postDetail/DefaultBanner/DefaultBanner.module.scss, src/components/postDetail/DefaultBanner/index.tsx, src/components/postDetail/PostDetailContent/index.tsx, src/constants/postForm.ts
- issue: #
- close #
- 유저가 사진을 한 장만 등록했을 경우 해당 사진에 카테고리와 게임 종류 글자를 표시하지 않고, 클릭하여 확대 가능하도록 수정
-
-
-
-
-
=> Refactor: DefaultBanner의 조건부 렌더링 로직 수정

src/components/commons/cards/RegisteredCard.tsx, src/components/landing/Echo/Echo.module.scss
- issue: #
- close #
- [마이페이지] 등록한 게시글 모달창 문구 변경
- [랜딩페이지] 화면 크기 변경시 에코가 화면을 벗어나는 오류 해결
=> Hotfix: 등록한 게시글 모달창 문구 변경, 에코 탈출 오류 해결

src/components/layout/header/AlarmCard/index.tsx, src/components/layout/header/AlarmList/AlarmList.module.scss, src/components/layout/header/AlarmList/index.tsx
- issue: #
- close #
- AlarmCard : 알림 메시지 title + 알림 문구로 가공했습니다.
- AlarmList : 전체 삭제 클릭시 모달 삭제하고, 전체 삭제 버튼 hover 추가했습니다.
=> Hotfix: AlarmCard & AlarmList 리팩토링

src/components/listPage/ListPageContent/index.tsx, src/components/listPage/PostList/index.tsx, src/components/mypage/MyPosts/index.tsx, src/components/mypage/MyReservations/ReservedTabContent/index.tsx
- issue: #
- close #
- 등록된 전체 게시글 및 마이페이지 리스트 로딩중일 경우 스켈레톤 카드 UI 적용했습니다.
-
- 스켈레톤 UI 적용
-
-
-
=> Feat: 리스트 로딩중일 경우 스켈레톤 카드 UI 적용

src/components/AccountForm/index.tsx
- issue: #
- close #
-  account 페이지 파일 첨부에서 이미지 등록으로 문구 변경했습니다.
=> Hotfix: account 페이지 파일 첨부에서 이미지 등록으로 문구 변경

src/components/auth/AuthInputField/AuthInputField.module.scss
- issue: #
- close #
-  AuthInputfield 자동완성시 css 수정했습니다
-  배경을 inherit으로 폰트 컬러를 white로 변경했습니다.
=> Hotfix: AuthInputfield 자동완성시 css 수정

src/components/landing/MatchTeam/MatchCards.module.scss, src/components/landing/MatchTeam/MatchCards.tsx
- issue: #
- close #
- MatchCard default일 때 이미지 가운데 정렬되도록 수정했습니다.
=> Hotfix: MatchCard default일 때 이미지 가운데 정렬되도록 수정

src/components/calendar/ListBody/ListBody.module.scss, src/components/calendar/ListCard/ListCard.module.scss
- issue: #
- close #
- 캘린더 scss에서 미리 정의된 믹스인을 사용하도록 수정
=> Hotfix: 캘린더 scss에서 미리 정의된 믹스인을 사용하도록 수정

src/components/layout/header/UserMenu/index.tsx, src/utils/signout.ts
- issue: #
- close #
- 로그아웃 안되는 이슈 해결
=> Hotfix: 로그아웃 안되는 이슈 해결

public/robots.txt, src/pages/_document.tsx
- issue: #
- close #
- document에 파비콘 추가했습니다.
- public에 robots.txt 추가하였습니다.
=> Hotfix: document에 파비콘 추가 및 robots.txt 추가

src/components/AccountForm/index.tsx, src/components/commons/Dropdown/index.tsx, src/components/commons/Filter/Filter.module.scss, src/components/commons/ProfileSummary/profileSummary.module.scss, src/components/commons/Tab/Tab.module.scss, src/components/commons/Tag/Tag.module.scss, src/components/commons/cards/CardCommonStyle.module.scss, src/components/commons/chatbot/ChatbotButton.tsx, src/components/commons/inputs/FormDropdown.tsx, src/components/commons/inputs/InputField.tsx, src/components/commons/inputs/PostFormDropdown.tsx, src/components/commons/inputs/TextField.tsx, src/components/layout/Footer/Footer.module.scss, src/components/postDetail/ReviewSummary/ReviewSummary.module.scss, src/constants/metaData.ts, src/pages/[game]/[postId]/index.tsx, src/pages/[game]/create/index.tsx, src/pages/[game]/edit/[activityId]/index.tsx, src/pages/[game]/index.tsx, src/pages/account/index.tsx, src/pages/mypage/index.tsx, src/pages/signin/index.tsx, src/pages/signup/index.tsx, src/styles/variables/_colors.scss
- issue: #
- close #
- 페이지별 메타 데이터, 타이틀 추가
- 웹접근성을 위한 form 요소별 aria 속성 추가
=> Hotfix: 페이지별 메타 데이터, 타이틀 추가 및 웹접근성을 위한 form 요소별 aria 속성 추가

src/components/commons/cards/ReservedCard.tsx, src/components/mypage/MyReservations/ReservedTabContent/index.tsx, src/stories/ReservedCard.stories.ts
- issue: #
- close #
- 기존 예약 카드의 생성 date를 사용자가 예약한 date로 변경했습니다.
=> Hotfix: 기존 예약 카드의 date 값을 사용자가 예약한 시간을 나타내는 것으로 변경

src/components/auth/SigninForm/SigninForm.module.scss, src/components/auth/SignupForm/SignupForm.module.scss
- issue: #
- close #
1.  signinform: container의 position relative 삭제했습니다.
2. signupform:  image에 image-fit 추가했습니다.
=> Hotfix: signinform signupform 이미지 css 수정

src/components/postDetail/MapPreview/index.tsx
- issue: #
- close #
- 상세보기 페이지에서 MapPreview에 address 값이 없다는 경고를 해결하기 위해 address에 기본값을 추가했습니다.
=> Hotfix: MapPreview address 기본값 추가

src/components/landing/ClanRecruitment/ClanRecruitment.tsx
- issue: #
- close #
- 저장된 queryKey 상수 파일 적용하였습니다.
-
-
-
-
-
=> Hotfix: 마이페이지 게임 리스트 queryKey 저장된 상수 파일 사용

src/components/createPage/PostForm/index.tsx
- issue: #
- close #
- 디스코드 글자 수 제한 50자로 수정
-
-
-
-
-
=> Hotfix: 디스코드 글자 수 제한 50자로 수정

src/components/createPage/PostForm/index.tsx
- issue: #
- close #
- 등록 페이지에서 입력 받은 주소가 없을 시 기본 값이 들어가지 않는 오류 수정
-
-
-
-
-
=> Hotfix: 등록 페이지 address 오류 수정

src/components/editPage/EditForm/index.tsx
- issue: #
- close #
- 수정 페이지 주소 및 디스코드 글자 수 제한 추가
-
-
-
-
-
=> Hotfix: 수정 페이지 주소 및 디스코드 글자 수 제한 추가

src/components/AccountForm/index.tsx
- issue: #
- close #
- 이미지 첨부 버튼 타입 submit 으로 수정했습니다.
=> Hotfix: 이미지 첨부 버튼 타입 submit 으로 수정

src/components/calendar/CalendarBody/index.tsx, src/components/calendar/index.tsx
- issue: #
- close #
- 종료 스케줄밖에 없는 날짜 클릭시 오류 뜨는것 해결
=> Hotfix: [마이페이지] 예약현황 - 예약 스케줄 정보가 있을때만 모달창 열리도록 수정

src/components/landing/ClanRecruitment/ClanRecruitment.module.scss
- issue: #
- close #
- 태블릿 이하 디바이스에서 슬라이더 아이템이 영역 밖으로 넘치는 문제 해결했습니다.
-
-
-
-
-
=> Hotfix: 랜딩페이지-태블릿 이하 디바이스에서 슬라이더가 영역 밖으로 나오는 문제 해결

src/apis/axios.ts, src/apis/ssrInstance.ts, src/apis/userInstance.ts, src/constants/auth.ts, src/pages/signin/index.tsx, src/pages/signup/index.tsx, src/utils/checkAuth.ts, src/utils/cookieUtils.ts
- issue: #
- close #
1. 토큰 갱신후 header에 첨부, intercepter request 로직 함수로 분리, tiemout 상수로 분리했습니다.
2. 로그인, 회원가입 페이지에서 토큰 갱신 후 게시판으로 이동되도록 수정했습니다.
3. renewAccess에서 isRenewed 리턴하도록 수정했습니다.
=> Hotfix: CSR 토큰 갱신 버그 해결, 로그인/회원가입 페이지에서 토큰 갱신 후 게시판 이동

src/components/postDetail/PostDesciption/PostDescription.module.scss, src/styles/variables/_box-shadow.scss
- issue: #
- close #
- 디스코드 링크 버튼 contrast ratio 기준에 적합한 배경색으로 변경했습니다.
-
-
-
-
-
=> Hotfix: 웹접근성 고려 contrast ratio 기준에 적합한 배경색으로 변경, 아이콘 중앙정렬

src/components/createPage/PostForm/index.tsx, src/components/layout/header/Menu/index.tsx
- issue: #
- close #
- Menu 컴포넌트에서 게임 클릭 시 query의 postType 값을 동적으로 변경하도록 수정
- 등록 페이지에서 취소 버튼 클릭 시 query의 postType을 all로 초기화하도록 수정
-
-
-
-
-
=> Refactor: query의 postType 동적으로 변경되도록 수정

src/constants/times.ts, src/hooks/useAlarmData.ts
- issue: #
- close #
- 알림 데이터 5분마다 리패치 되도록 refetchInterval 적용했습니다.
=> Hotfix: 알림 데이터 1분마다 리패치 되도록 refetchInterval 적용

src/pages/landing/index.tsx
- issue: #
- close #
- 게시글 목록 queryKey 상수 파일 적용
-
-
-
-
-
=> hotfix: 게시글 목록 queryKey 상수 파일 적용

src/components/landing/MatchTeam/MatchCards.module.scss
- issue: #
- close #
- 랜딩페이지 MatchCard default 이미지 축소 버그 수정했습니다.
=> Hotfix: 랜딩페이지 MatchCard default 이미지 축소 버그 수정

src/utils/getDate.ts
- issue: #
- close #
- getFormatDate 유틸 함수를 utc로 수정
-
-
-
-
-
=> Hotfix: getFormatDate 유틸 함수를 utc로 수정

src/hooks/useSignout.ts, src/utils/getDate.ts
- issue: #
- close #
- 로그아웃 커스텀 훅의 destroyCookie 옵션에 path 추가
- getFormatDate 유틸 함수를 utc로 수정
-
-
-
-
-
=> Hotfix: destroyCookie 옵션에 path 추가

src/apis/activities/schema.ts, src/components/createPage/PostForm/index.tsx, src/components/editPage/EditForm/index.tsx, src/constants/postForm.ts
- issue: #
- close #
- 등록 및 수정 페이지 스키마 분리
-
-
-
-
-
=> Refactor: 등록 및 수정 페이지 스키마 분리

src/components/commons/cards/CommonCard.tsx
- issue: #
- close #
- common card: post type이 온라인, 오프라인일 경우에만 평점 보여주도록 수정
-
-
-
-
-
=> Refactor: 온라인, 오프라인 모집 카드만 평점을 보여주도록 수정

src/components/commons/chatbot/Chatbot.tsx, src/components/commons/chatbot/data-access/useRequestAnswer.ts
- issue: #
- close #
- 질문 입력 후 input의 value가 그대로 남아있는 문제 해결(답변을 받고 사라지는 문제)
=> Fix: 질문 입력 후 input에 value가 그대로 남아있는 문제 해결

src/components/commons/chatbot/Chatbot.tsx, src/components/commons/chatbot/data-access/useRequestAnswer.ts
=> Deploy Version 1.4

src/components/landing/ClanRecruitment/ClanRecruitment.tsx, src/constants/images.ts
- issue: #
- close #
- [ O ] 버그 해결
개인 AWS 프리티어 계정에 업로드했던 이미지들을 코드잇 s3 로 이동
=> feat: 이미지 코드잇 s3로 이동
